### PR TITLE
Fix/proxy payment

### LINKED ISSUE #738: Do not change capitalization in organization names
When Paul created an organization, he entered in WLC2. When the organization was created, it resulted in Wlc2 and LC became uncapitalized. 
Screenshot 2023-09-23 at 8 59 31 AM

We should preserve whatever capitalization the user enters when creating an organization.

### LINKED ISSUE #739: Bounty payment failed through organization
Paul funded an org with 10,000 sats. Created a bounty and tied an org to it. Tried paying 9,998. Then 1000 sats. Both attempts failed to paying to Andrew.

This might be a result that we haven't enabled sending to a proxy user. Andrew was able to successfully send to kev, but was unable to send to raph who is a proxy user. Andrew is also a proxy user.

### PR DESCRIPTION
**Pull request by elraphty**
## Describe your changes

This PR removes the capitalization of organization names and adds a route hint for proxy users' keysend payments.

## Issue ticket number and link

Closes #739 
Closes #738

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device

### CODE REVIEW

File: handlers/bounty.go [hunk 1]
```diff
@@ -311,7 +311,14 @@ func MakeBountyPayment(w http.ResponseWriter, r *http.Request) {
...
 
 	url := fmt.Sprintf("%s/payment", config.RelayUrl)
-	bodyData := fmt.Sprintf(`{"amount": %d, "destination_key": "%s"}`, amount, request.ReceiverPubKey)
+
+	var bodyData string
+	if request.RouteHint != "" {
+		bodyData = fmt.Sprintf(`{"amount": %d, "destination_key": "%s", "route_hint": "%s"}`, amount, request.ReceiverPubKey, request.RouteHint)
+	} else {
+		bodyData = fmt.Sprintf(`{"amount": %d, "destination_key": "%s"}`, amount, request.ReceiverPubKey)
+	}
```
Comment (kevkevinpal) [inline handlers/bounty.go:320]: Looks like were doing this in two locations it might make more sense to make this a util than repeating code

File: handlers/invoiceCron.go [hunk 2]
```diff
@@ -71,7 +71,12 @@ func InitInvoiceCron() {
 						if inv.Type == "KEYSEND" {
 							url := fmt.Sprintf("%s/payment", config.RelayUrl)
 
-							bodyData := fmt.Sprintf(`{"amount": %s, "destination_key": "%s"}`, inv.Amount, inv.User_pubkey)
+							var bodyData string
+							if inv.Route_hint != "" {
+								bodyData = fmt.Sprintf(`{"amount": %s, "destination_key": "%s", "route_hint": "%s"}`, inv.Amount, inv.User_pubkey, inv.Route_hint)
+							} else {
+								bodyData = fmt.Sprintf(`{"amount": %s, "destination_key": "%s"}`, inv.Amount, inv.User_pubkey)
+							}
```
Comment (kevkevinpal) [inline handlers/invoiceCron.go:79]: Looks like were doing this in two locations it might make more sense to make this a util than repeating code

**Review by kevkevinpal — COMMENTED** [review]
looks good to me if you could make that one part a util to make it more common that would be good

File: handlers/invoiceCron.go (hunk 2 above)
Comment (elraphty) [reply handlers/invoiceCron.go]: I have created a util function for it.

**Comment by kevkevinpal** [comment]
looks good to me merging
